version: "3.9"

services:
  db:
    image: mysql:8.1
    container_name: todolist-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: .
    container_name: myapp-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/todolist?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - maven-repo:/root/.m2
    working_dir: /app

  test:
    image: maven:3.9.5-eclipse-temurin-21
    working_dir: /app
    volumes:
      - maven-repo:/root/.m2
    command: sh -c "git clone https://github.com/MojaveMix/devsecops-pipeline.git . && mvn test"
volumes:
  db-data:
  maven-repo:
